### Numpy

In [2]:
import numpy as np
import time

In [3]:
arr =  np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
arr =  np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
size = 10_000_000

# Python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time = {end-start} seconds")

# Numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"Numpy array time = {end-start} seconds")

Python list time = 1.3304104804992676 seconds
Numpy array time = 0.06424379348754883 seconds


In [6]:
# Memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


In [7]:
# Create - from list
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> <U21 (6,)


In [8]:
#2D Arrays
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [9]:
# create
arr1 = np.zeros((2, 3), dtype="int64") #Prefill
print(arr1, arr1.shape)

arr2 = np.ones((2, 3), dtype="int64") #Prefill
print(arr2, arr2.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)


In [10]:
arr2 = np.ones((5, ), ) #Prefill
print(arr2, arr2.shape)

arr2 = np.full((3, 4), 100) #Prefill
print(arr2, arr2.shape)

[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [11]:
arr2 = np.eye(4) #Prefill
print(arr2, arr2.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)


In [12]:
arr2 = np.full((3, 4), 100) #Prefill
print(arr2, arr2.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [13]:
arr3 = np.arange(1, 11, 2) #Prefill
print(arr3, arr3.shape)

arr4 = np.arange(0, 11, 2) #Prefill
print(arr4, arr4.shape)

[1 3 5 7 9] (5,)
[ 0  2  4  6  8 10] (6,)


In [14]:
arr4 = np.linspace(1, 100, 3) #Prefill
print(arr4, arr4.shape)

[  1.   50.5 100. ] (3,)


In [15]:
# Properties
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape) # dimensions = m x n

(5,)


In [16]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 6, 8]])
print(arr.shape) # dimensions = m x n
print(arr.size)
print(arr.dtype)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype )

(3, 3)
9
int64
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 6. 8.]] float64


In [17]:
# Operations on arrays

#Reshape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattend = arr.flatten() # 20 => 1D
print(flattend, flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [18]:
# Indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])
print(arr[3])

1
4


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0][2])
print(arr[1][1])

3
5


In [20]:
# Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [21]:
# Fancy & Boolean Indexing

arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr < 4])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[1 2 3]
[2 4]
[1 3 5]


In [22]:
# Slicing
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [23]:
# Copy vs View

nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [24]:
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[  1 200   3   4   5]


In [25]:
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [26]:
# Data Types
arr = np.array([1, 2, 3.14, 4, 5])
print(arr, arr.dtype)

[1.   2.   3.14 4.   5.  ] float64


In [27]:
# Data Types
arr = np.array([1, 2, 3.14, 4, 5, "Prime"])
print(arr, arr.dtype)

['1' '2' '3.14' '4' '5' 'Prime'] <U32


In [28]:
# Data Type

arr = np.array([3 + 5j])
print(arr, arr.dtype)

[3.+5.j] complex128


In [29]:
# Data Type

arr1 = np.array([3 + 5j])
arr2 = np.array([2 + 3j])

print(arr1 + arr2)
print(arr1 - arr2)

[5.+8.j]
[1.+2.j]


In [30]:
# Data Types 

arr = np.array(["Prime", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

['Prime' {1, 2, 3} 3.14] object


In [31]:
# Multi-dimensional arrays

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [32]:
# 3D Array

arr3D = np.array([[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]])

print(arr3D, arr3D.shape)

print(arr3D[0, 1, 1])

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]] (1, 6, 2)
4


In [33]:
# 3D Array

arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])

print(arr3D, arr3D.shape)

print(arr3D[1, 1, 0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9


In [34]:
# 3D Array

arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])

print(arr3D, arr3D.shape)

print(arr3D[1, 0, 1])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
8


In [35]:
#3D Array

arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])

print(arr3D, arr3D.shape)

#Indexing
print(arr3D[1, 1, 0])

#Slicing
arr3D[:, 0, :] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [36]:
#vectorization
arr = np.array([1, 2, 3, 4, 5])
print(arr ** 2)

[ 1  4  9 16 25]


In [37]:
#vectorization
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)

[11 12 13 14 15]


In [38]:
#vectorization
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr + arr2)

[ 7  9 11 13 15]


In [39]:
#broadcasting

arr = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(arr.shape)
print(arr2.shape)

print(arr + arr2)

(2, 5)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [40]:
#normalize
arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [41]:
#Mathematical fnx

#aggregation

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [42]:
#Power fnx

arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [43]:
#log

arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [44]:
#rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1, 2, -8, 3, 4, -5, 2, 5])

print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr))

3.0
4.0
3.0
3.0
[-8 -5  1  2  3  4  5]
[-8 -5  1  2  2  3  4  5]
[1 2 8 3 4 5 2 5]
